### ISSUE TITLE
How do you set branches

### ISSUE THREAD

**Issue by RampedIndent** [semantic-release-action/next-release-version#11]
I keep getting this error because i'm not using the master branch
```
      code: 'ERELEASEBRANCHES',
      details: 'A minimum of 1 and a maximum of 3 release branches are required in the [branches configuration](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).\n' +
        '\n' +
        'This may occur if your repository does not have a release branch, such as `master`.\n' +
        '\n' +
        'Your configuration for the problematic branches is `[]`.',
```

**Comment by EricCrosson** [comment]
I don't have enough information to know what might be happening here. Are you able to link to GitHub Actions logs and your repository?

**Comment by EricCrosson** [comment]
Hmm, could be because `main` isn't in the default list of release branches[^1]. This looks related: https://semantic-release.gitbook.io/semantic-release/usage/configuration#branches

[^1]: https://semantic-release.gitbook.io/semantic-release/usage/configuration#branches

**Comment by RampedIndent** [comment]
Im pretty sure ive set main in the   [.releaserc](https://github.com/RampedIndent/polylauncher/blob/bef62cb0c71c6e7d775fe4b7eaf0f4ddf610857a/.releaserc.yaml#L2)


https://github.com/RampedIndent/polylauncher
https://github.com/RampedIndent/polylauncher/actions/runs/4233076111/jobs/7353573764#step:16:592

**Comment by RampedIndent** [comment]
The one time i managed to make semantic-release run successfully i had to set the branches in the workflow file
https://github.com/RampedIndent/polylauncher/actions/runs/4232522924/workflow

**Comment by EricCrosson** [comment]
This workflow ignores your repository's semantic-release configuration[^1]. From that link:

```yaml
    # Clear out any existing semantic-release configuration.
    #
    # This step is necessary in my projects that use a .releaserc.json file
    # with a non-stock semantic-release plugin, because semantic-release throws
    # an error when the plugin is referenced in the configuration but not
    # present in the node_modules directory.
    #
    # Therefore, a quick and drity workaround is to clear out the configuration
    # before invoking semantic-release.
```

This means semantic-release's default value for `branches`[^2] is used. We could hack in support for `main` branches specifically, but it seems more desirable to support the host repository's arbitrary `branches` configuration.

[^1]: https://github.com/semantic-release-action/next-release-version/blob/51270e55e25801f8a2846f0e581c85323190503d/internal/action.yml#L77
[^2]: https://semantic-release.gitbook.io/semantic-release/usage/configuration#branches

**Comment by RampedIndent** [comment]
> This workflow ignores your repository's semantic-release configuration[1](#user-content-fn-1-0d2a9422ec89f42d2d4a0efab5ccf0c1). From that link:

is that step only necessary for .releaserc files that use non stock semantic release plugins?
if so maybe there could be a toggle to disable that step if it is not necessary

**Comment by RampedIndent** [comment]
the command `yq '.branches | {"branches": .}' .releaserc.yaml  > .releaserc.json` will isolate the branches and convert them to json

**Comment by RampedIndent** [comment]
Implimented a fix for .json , .yml, and .yaml files that should work

**Comment by EricCrosson** [comment]
> Should probably just delete the plugins section

This is the approach I was leaning towards too, but it turns out we can override the `plugins` section with a CLI option. Please give it a shot and let me know if the issue is resolved!

**Comment by RampedIndent** [comment]
it runs successfully after i commented out some additional sections in my .releaserc

**Comment by EricCrosson** [comment]
Hmm, were these the necessary changes? https://github.com/RampedIndent/polylauncher/commit/e9415015203be7b28086dcd158698d51c370ad4c

**Comment by RampedIndent** [comment]
I got this error so i commented out all the stuff that i figured wasn't required.
https://github.com/RampedIndent/polylauncher/actions/runs/4273772915/jobs/7439904486

**Comment by EricCrosson** [comment]
Thanks for the link, copying the error here for posterity

```
Run : calculate next semantic-release version
[6:42:41 AM] [semantic-release] › ℹ  Running semantic-release version 20.1.0
[6:42:41 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "semantic-release-export-data"
[6:42:41 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[6:42:41 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "semantic-release-export-data"
[6:42:41 AM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Cannot find module '@semantic-release/git'
Require stack:
- /home/runner/work/polylauncher/polylauncher/noop.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at resolveFileName (/home/runner/work/_temp/.semantic-release-action_next-release-version/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/work/_temp/.semantic-release-action_next-release-version/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/work/_temp/.semantic-release-action_next-release-version/node_modules/resolve-from/index.js:46:47)
    at loadPlugin (file:///home/runner/work/_temp/.semantic-release-action_next-release-version/node_modules/semantic-release/lib/plugins/utils.js:59:54)
    at default (file:///home/runner/work/_temp/.semantic-release-action_next-release-version/node_modules/semantic-release/lib/plugins/normalize.js:18:24)
    at file:///home/runner/work/_temp/.semantic-release-action_next-release-version/node_modules/semantic-release/lib/plugins/index.js:76:11
    at Array.map (<anonymous>)
    at file:///home/runner/work/_temp/.semantic-release-action_next-release-version/node_modules/semantic-release/lib/plugins/index.js:75:34
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/polylauncher/polylauncher/noop.js' ]
}
```

**Comment by EricCrosson** [comment]
I found a way to mitigate this issue, using the same pattern: 538bd6f

Thank you for the bug reports!
